# Automatically generated by pb2py
import protobuf as p
from .ButtonRequestType import ButtonRequestType


class ButtonRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 26
    FIELDS = {
        1: ('code', ButtonRequestType, 0),
        2: ('data', p.UnicodeType, 0),
    }

    def __init__(
        self,
        code: ButtonRequestType = None,
        data: str = None
    ) -> None:
        self.code = code
        self.data = data
