# Automatically generated by pb2py
import protobuf as p
from .NEMModificationType import NEMModificationType


class NEMCosignatoryModification(p.MessageType):
    FIELDS = {
        1: ('type', NEMModificationType, 0),
        2: ('public_key', p.BytesType, 0),
    }

    def __init__(
        self,
        type: NEMModificationType = None,
        public_key: bytes = None
    ) -> None:
        self.type = type
        self.public_key = public_key
