# Automatically generated by pb2py
import protobuf as p
from .NEMImportanceTransferMode import NEMImportanceTransferMode


class NEMImportanceTransfer(p.MessageType):
    FIELDS = {
        1: ('mode', NEMImportanceTransferMode, 0),
        2: ('public_key', p.BytesType, 0),
    }

    def __init__(
        self,
        mode: NEMImportanceTransferMode = None,
        public_key: bytes = None
    ) -> None:
        self.mode = mode
        self.public_key = public_key
