# Automatically generated by pb2py
import protobuf as p
from .NEMSupplyChangeType import NEMSupplyChangeType


class NEMMosaicSupplyChange(p.MessageType):
    FIELDS = {
        1: ('namespace', p.UnicodeType, 0),
        2: ('mosaic', p.UnicodeType, 0),
        3: ('type', NEMSupplyChangeType, 0),
        4: ('delta', p.UVarintType, 0),
    }

    def __init__(
        self,
        namespace: str = None,
        mosaic: str = None,
        type: NEMSupplyChangeType = None,
        delta: int = None
    ) -> None:
        self.namespace = namespace
        self.mosaic = mosaic
        self.type = type
        self.delta = delta
