# Automatically generated by pb2py
import protobuf as p
from .PinMatrixRequestType import PinMatrixRequestType


class PinMatrixRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 18
    FIELDS = {
        1: ('type', PinMatrixRequestType, 0),
    }

    def __init__(
        self,
        type: PinMatrixRequestType = None
    ) -> None:
        self.type = type
