# Automatically generated by pb2py
import protobuf as p
from .WordRequestType import WordRequestType


class WordRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 46
    FIELDS = {
        1: ('type', WordRequestType, 0),
    }

    def __init__(
        self,
        type: WordRequestType = None
    ) -> None:
        self.type = type
